#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_BookOnline
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BookOnline")]
	public partial class DataClassesBookOnlineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Account(tbl_Account instance);
    partial void Updatetbl_Account(tbl_Account instance);
    partial void Deletetbl_Account(tbl_Account instance);
    partial void Inserttbl_TransactionInfo(tbl_TransactionInfo instance);
    partial void Updatetbl_TransactionInfo(tbl_TransactionInfo instance);
    partial void Deletetbl_TransactionInfo(tbl_TransactionInfo instance);
    partial void Inserttbl_Annotation(tbl_Annotation instance);
    partial void Updatetbl_Annotation(tbl_Annotation instance);
    partial void Deletetbl_Annotation(tbl_Annotation instance);
    partial void Inserttbl_Author(tbl_Author instance);
    partial void Updatetbl_Author(tbl_Author instance);
    partial void Deletetbl_Author(tbl_Author instance);
    partial void Inserttbl_Book(tbl_Book instance);
    partial void Updatetbl_Book(tbl_Book instance);
    partial void Deletetbl_Book(tbl_Book instance);
    partial void Inserttbl_BookofUser(tbl_BookofUser instance);
    partial void Updatetbl_BookofUser(tbl_BookofUser instance);
    partial void Deletetbl_BookofUser(tbl_BookofUser instance);
    partial void Inserttbl_Catalog(tbl_Catalog instance);
    partial void Updatetbl_Catalog(tbl_Catalog instance);
    partial void Deletetbl_Catalog(tbl_Catalog instance);
    partial void Inserttbl_Comment(tbl_Comment instance);
    partial void Updatetbl_Comment(tbl_Comment instance);
    partial void Deletetbl_Comment(tbl_Comment instance);
    partial void Inserttbl_Follow(tbl_Follow instance);
    partial void Updatetbl_Follow(tbl_Follow instance);
    partial void Deletetbl_Follow(tbl_Follow instance);
    partial void Inserttbl_Rating(tbl_Rating instance);
    partial void Updatetbl_Rating(tbl_Rating instance);
    partial void Deletetbl_Rating(tbl_Rating instance);
    partial void Inserttbl_TransactionHistory(tbl_TransactionHistory instance);
    partial void Updatetbl_TransactionHistory(tbl_TransactionHistory instance);
    partial void Deletetbl_TransactionHistory(tbl_TransactionHistory instance);
    #endregion
		
		public DataClassesBookOnlineDataContext() : 
				base(global::DAL_BookOnline.Properties.Settings.Default.BookOnlineConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesBookOnlineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesBookOnlineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesBookOnlineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesBookOnlineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Account> tbl_Accounts
		{
			get
			{
				return this.GetTable<tbl_Account>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TransactionInfo> tbl_TransactionInfos
		{
			get
			{
				return this.GetTable<tbl_TransactionInfo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Annotation> tbl_Annotations
		{
			get
			{
				return this.GetTable<tbl_Annotation>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Author> tbl_Authors
		{
			get
			{
				return this.GetTable<tbl_Author>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Book> tbl_Books
		{
			get
			{
				return this.GetTable<tbl_Book>();
			}
		}
		
		public System.Data.Linq.Table<tbl_BookofUser> tbl_BookofUsers
		{
			get
			{
				return this.GetTable<tbl_BookofUser>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Catalog> tbl_Catalogs
		{
			get
			{
				return this.GetTable<tbl_Catalog>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Comment> tbl_Comments
		{
			get
			{
				return this.GetTable<tbl_Comment>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DanhMuc> tbl_DanhMucs
		{
			get
			{
				return this.GetTable<tbl_DanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Follow> tbl_Follows
		{
			get
			{
				return this.GetTable<tbl_Follow>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Package> tbl_Packages
		{
			get
			{
				return this.GetTable<tbl_Package>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Rating> tbl_Ratings
		{
			get
			{
				return this.GetTable<tbl_Rating>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TransactionHistory> tbl_TransactionHistories
		{
			get
			{
				return this.GetTable<tbl_TransactionHistory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Account")]
	public partial class tbl_Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AccountID;
		
		private string _NAME;
		
		private string _PWD;
		
		private bool _GEN;
		
		private System.Nullable<decimal> _Wallet;
		
		private System.Data.Linq.Binary _IMG;
		
		private string _NOTE;
		
		private System.Nullable<System.DateTime> _RemainingTime;
		
		private int _Status;
		
		private System.DateTime _SignupDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIDChanging(string value);
    partial void OnAccountIDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPWDChanging(string value);
    partial void OnPWDChanged();
    partial void OnGENChanging(bool value);
    partial void OnGENChanged();
    partial void OnWalletChanging(System.Nullable<decimal> value);
    partial void OnWalletChanged();
    partial void OnIMGChanging(System.Data.Linq.Binary value);
    partial void OnIMGChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnRemainingTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnRemainingTimeChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnSignupDateChanging(System.DateTime value);
    partial void OnSignupDateChanged();
    #endregion
		
		public tbl_Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(20)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PWD", DbType="NVarChar(12)")]
		public string PWD
		{
			get
			{
				return this._PWD;
			}
			set
			{
				if ((this._PWD != value))
				{
					this.OnPWDChanging(value);
					this.SendPropertyChanging();
					this._PWD = value;
					this.SendPropertyChanged("PWD");
					this.OnPWDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GEN", DbType="Bit NOT NULL")]
		public bool GEN
		{
			get
			{
				return this._GEN;
			}
			set
			{
				if ((this._GEN != value))
				{
					this.OnGENChanging(value);
					this.SendPropertyChanging();
					this._GEN = value;
					this.SendPropertyChanged("GEN");
					this.OnGENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wallet", DbType="Money")]
		public System.Nullable<decimal> Wallet
		{
			get
			{
				return this._Wallet;
			}
			set
			{
				if ((this._Wallet != value))
				{
					this.OnWalletChanging(value);
					this.SendPropertyChanging();
					this._Wallet = value;
					this.SendPropertyChanged("Wallet");
					this.OnWalletChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMG", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary IMG
		{
			get
			{
				return this._IMG;
			}
			set
			{
				if ((this._IMG != value))
				{
					this.OnIMGChanging(value);
					this.SendPropertyChanging();
					this._IMG = value;
					this.SendPropertyChanged("IMG");
					this.OnIMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="Char(100)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainingTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> RemainingTime
		{
			get
			{
				return this._RemainingTime;
			}
			set
			{
				if ((this._RemainingTime != value))
				{
					this.OnRemainingTimeChanging(value);
					this.SendPropertyChanging();
					this._RemainingTime = value;
					this.SendPropertyChanged("RemainingTime");
					this.OnRemainingTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignupDate", DbType="DateTime NOT NULL")]
		public System.DateTime SignupDate
		{
			get
			{
				return this._SignupDate;
			}
			set
			{
				if ((this._SignupDate != value))
				{
					this.OnSignupDateChanging(value);
					this.SendPropertyChanging();
					this._SignupDate = value;
					this.SendPropertyChanged("SignupDate");
					this.OnSignupDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TransactionInfo")]
	public partial class tbl_TransactionInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TransactionID;
		
		private string _ProductID;
		
		private System.DateTime _TransactionDate;
		
		private string _ProductName;
		
		private System.Nullable<int> _Quantity;
		
		private System.Nullable<decimal> _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    partial void OnProductIDChanging(string value);
    partial void OnProductIDChanged();
    partial void OnTransactionDateChanging(System.DateTime value);
    partial void OnTransactionDateChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnQuantityChanging(System.Nullable<int> value);
    partial void OnQuantityChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    #endregion
		
		public tbl_TransactionInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this.OnTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._TransactionID = value;
					this.SendPropertyChanged("TransactionID");
					this.OnTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime TransactionDate
		{
			get
			{
				return this._TransactionDate;
			}
			set
			{
				if ((this._TransactionDate != value))
				{
					this.OnTransactionDateChanging(value);
					this.SendPropertyChanging();
					this._TransactionDate = value;
					this.SendPropertyChanged("TransactionDate");
					this.OnTransactionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(200)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Annotation")]
	public partial class tbl_Annotation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Annotation_id;
		
		private string _book_id;
		
		private string _book_name;
		
		private string _user_id;
		
		private string _user_name;
		
		private string _Annotation_text;
		
		private System.Nullable<int> _page_number;
		
		private string _Annotation_type;
		
		private string _Annotation_color;
		
		private System.Nullable<System.DateTime> _creationDate;
		
		private System.Nullable<System.DateTime> _modificationDate;
		
		private string _Subject;
		
		private System.Nullable<decimal> _QX1;
		
		private System.Nullable<decimal> _qy1;
		
		private System.Nullable<decimal> _qx2;
		
		private System.Nullable<decimal> _qy2;
		
		private System.Nullable<decimal> _qx3;
		
		private System.Nullable<decimal> _qy3;
		
		private System.Nullable<decimal> _qx4;
		
		private System.Nullable<decimal> _qy4;
		
		private string _Annotation_Comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAnnotation_idChanging(int value);
    partial void OnAnnotation_idChanged();
    partial void Onbook_idChanging(string value);
    partial void Onbook_idChanged();
    partial void Onbook_nameChanging(string value);
    partial void Onbook_nameChanged();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnAnnotation_textChanging(string value);
    partial void OnAnnotation_textChanged();
    partial void Onpage_numberChanging(System.Nullable<int> value);
    partial void Onpage_numberChanged();
    partial void OnAnnotation_typeChanging(string value);
    partial void OnAnnotation_typeChanged();
    partial void OnAnnotation_colorChanging(string value);
    partial void OnAnnotation_colorChanged();
    partial void OncreationDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreationDateChanged();
    partial void OnmodificationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodificationDateChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnQX1Changing(System.Nullable<decimal> value);
    partial void OnQX1Changed();
    partial void Onqy1Changing(System.Nullable<decimal> value);
    partial void Onqy1Changed();
    partial void Onqx2Changing(System.Nullable<decimal> value);
    partial void Onqx2Changed();
    partial void Onqy2Changing(System.Nullable<decimal> value);
    partial void Onqy2Changed();
    partial void Onqx3Changing(System.Nullable<decimal> value);
    partial void Onqx3Changed();
    partial void Onqy3Changing(System.Nullable<decimal> value);
    partial void Onqy3Changed();
    partial void Onqx4Changing(System.Nullable<decimal> value);
    partial void Onqx4Changed();
    partial void Onqy4Changing(System.Nullable<decimal> value);
    partial void Onqy4Changed();
    partial void OnAnnotation_CommentChanging(string value);
    partial void OnAnnotation_CommentChanged();
    #endregion
		
		public tbl_Annotation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annotation_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Annotation_id
		{
			get
			{
				return this._Annotation_id;
			}
			set
			{
				if ((this._Annotation_id != value))
				{
					this.OnAnnotation_idChanging(value);
					this.SendPropertyChanging();
					this._Annotation_id = value;
					this.SendPropertyChanged("Annotation_id");
					this.OnAnnotation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_id", DbType="VarChar(10)")]
		public string book_id
		{
			get
			{
				return this._book_id;
			}
			set
			{
				if ((this._book_id != value))
				{
					this.Onbook_idChanging(value);
					this.SendPropertyChanging();
					this._book_id = value;
					this.SendPropertyChanged("book_id");
					this.Onbook_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_name", DbType="NVarChar(255)")]
		public string book_name
		{
			get
			{
				return this._book_name;
			}
			set
			{
				if ((this._book_name != value))
				{
					this.Onbook_nameChanging(value);
					this.SendPropertyChanging();
					this._book_name = value;
					this.SendPropertyChanged("book_name");
					this.Onbook_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="VarChar(15)")]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(255)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annotation_text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Annotation_text
		{
			get
			{
				return this._Annotation_text;
			}
			set
			{
				if ((this._Annotation_text != value))
				{
					this.OnAnnotation_textChanging(value);
					this.SendPropertyChanging();
					this._Annotation_text = value;
					this.SendPropertyChanged("Annotation_text");
					this.OnAnnotation_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_number", DbType="Int")]
		public System.Nullable<int> page_number
		{
			get
			{
				return this._page_number;
			}
			set
			{
				if ((this._page_number != value))
				{
					this.Onpage_numberChanging(value);
					this.SendPropertyChanging();
					this._page_number = value;
					this.SendPropertyChanged("page_number");
					this.Onpage_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annotation_type", DbType="VarChar(50)")]
		public string Annotation_type
		{
			get
			{
				return this._Annotation_type;
			}
			set
			{
				if ((this._Annotation_type != value))
				{
					this.OnAnnotation_typeChanging(value);
					this.SendPropertyChanging();
					this._Annotation_type = value;
					this.SendPropertyChanged("Annotation_type");
					this.OnAnnotation_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annotation_color", DbType="VarChar(50)")]
		public string Annotation_color
		{
			get
			{
				return this._Annotation_color;
			}
			set
			{
				if ((this._Annotation_color != value))
				{
					this.OnAnnotation_colorChanging(value);
					this.SendPropertyChanging();
					this._Annotation_color = value;
					this.SendPropertyChanged("Annotation_color");
					this.OnAnnotation_colorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> creationDate
		{
			get
			{
				return this._creationDate;
			}
			set
			{
				if ((this._creationDate != value))
				{
					this.OncreationDateChanging(value);
					this.SendPropertyChanging();
					this._creationDate = value;
					this.SendPropertyChanged("creationDate");
					this.OncreationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> modificationDate
		{
			get
			{
				return this._modificationDate;
			}
			set
			{
				if ((this._modificationDate != value))
				{
					this.OnmodificationDateChanging(value);
					this.SendPropertyChanging();
					this._modificationDate = value;
					this.SendPropertyChanged("modificationDate");
					this.OnmodificationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(255)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QX1", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> QX1
		{
			get
			{
				return this._QX1;
			}
			set
			{
				if ((this._QX1 != value))
				{
					this.OnQX1Changing(value);
					this.SendPropertyChanging();
					this._QX1 = value;
					this.SendPropertyChanged("QX1");
					this.OnQX1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qy1", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> qy1
		{
			get
			{
				return this._qy1;
			}
			set
			{
				if ((this._qy1 != value))
				{
					this.Onqy1Changing(value);
					this.SendPropertyChanging();
					this._qy1 = value;
					this.SendPropertyChanged("qy1");
					this.Onqy1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qx2", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> qx2
		{
			get
			{
				return this._qx2;
			}
			set
			{
				if ((this._qx2 != value))
				{
					this.Onqx2Changing(value);
					this.SendPropertyChanging();
					this._qx2 = value;
					this.SendPropertyChanged("qx2");
					this.Onqx2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qy2", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> qy2
		{
			get
			{
				return this._qy2;
			}
			set
			{
				if ((this._qy2 != value))
				{
					this.Onqy2Changing(value);
					this.SendPropertyChanging();
					this._qy2 = value;
					this.SendPropertyChanged("qy2");
					this.Onqy2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qx3", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> qx3
		{
			get
			{
				return this._qx3;
			}
			set
			{
				if ((this._qx3 != value))
				{
					this.Onqx3Changing(value);
					this.SendPropertyChanging();
					this._qx3 = value;
					this.SendPropertyChanged("qx3");
					this.Onqx3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qy3", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> qy3
		{
			get
			{
				return this._qy3;
			}
			set
			{
				if ((this._qy3 != value))
				{
					this.Onqy3Changing(value);
					this.SendPropertyChanging();
					this._qy3 = value;
					this.SendPropertyChanged("qy3");
					this.Onqy3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qx4", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> qx4
		{
			get
			{
				return this._qx4;
			}
			set
			{
				if ((this._qx4 != value))
				{
					this.Onqx4Changing(value);
					this.SendPropertyChanging();
					this._qx4 = value;
					this.SendPropertyChanged("qx4");
					this.Onqx4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qy4", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> qy4
		{
			get
			{
				return this._qy4;
			}
			set
			{
				if ((this._qy4 != value))
				{
					this.Onqy4Changing(value);
					this.SendPropertyChanging();
					this._qy4 = value;
					this.SendPropertyChanged("qy4");
					this.Onqy4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annotation_Comment", DbType="NVarChar(MAX)")]
		public string Annotation_Comment
		{
			get
			{
				return this._Annotation_Comment;
			}
			set
			{
				if ((this._Annotation_Comment != value))
				{
					this.OnAnnotation_CommentChanging(value);
					this.SendPropertyChanging();
					this._Annotation_Comment = value;
					this.SendPropertyChanged("Annotation_Comment");
					this.OnAnnotation_CommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Author")]
	public partial class tbl_Author : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AuthorID;
		
		private string _AuthorNAME;
		
		private System.Nullable<bool> _GEN;
		
		private System.Nullable<System.DateTime> _BIRTHDAY;
		
		private string _COUNTRY;
		
		private string _SUMMARY;
		
		private string _IMG;
		
		private string _NOTE;
		
		private System.Nullable<int> _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuthorIDChanging(string value);
    partial void OnAuthorIDChanged();
    partial void OnAuthorNAMEChanging(string value);
    partial void OnAuthorNAMEChanged();
    partial void OnGENChanging(System.Nullable<bool> value);
    partial void OnGENChanged();
    partial void OnBIRTHDAYChanging(System.Nullable<System.DateTime> value);
    partial void OnBIRTHDAYChanged();
    partial void OnCOUNTRYChanging(string value);
    partial void OnCOUNTRYChanged();
    partial void OnSUMMARYChanging(string value);
    partial void OnSUMMARYChanged();
    partial void OnIMGChanging(string value);
    partial void OnIMGChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    #endregion
		
		public tbl_Author()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorID", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AuthorID
		{
			get
			{
				return this._AuthorID;
			}
			set
			{
				if ((this._AuthorID != value))
				{
					this.OnAuthorIDChanging(value);
					this.SendPropertyChanging();
					this._AuthorID = value;
					this.SendPropertyChanged("AuthorID");
					this.OnAuthorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorNAME", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string AuthorNAME
		{
			get
			{
				return this._AuthorNAME;
			}
			set
			{
				if ((this._AuthorNAME != value))
				{
					this.OnAuthorNAMEChanging(value);
					this.SendPropertyChanging();
					this._AuthorNAME = value;
					this.SendPropertyChanged("AuthorNAME");
					this.OnAuthorNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GEN", DbType="Bit")]
		public System.Nullable<bool> GEN
		{
			get
			{
				return this._GEN;
			}
			set
			{
				if ((this._GEN != value))
				{
					this.OnGENChanging(value);
					this.SendPropertyChanging();
					this._GEN = value;
					this.SendPropertyChanged("GEN");
					this.OnGENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHDAY", DbType="Date")]
		public System.Nullable<System.DateTime> BIRTHDAY
		{
			get
			{
				return this._BIRTHDAY;
			}
			set
			{
				if ((this._BIRTHDAY != value))
				{
					this.OnBIRTHDAYChanging(value);
					this.SendPropertyChanging();
					this._BIRTHDAY = value;
					this.SendPropertyChanged("BIRTHDAY");
					this.OnBIRTHDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY", DbType="NVarChar(100)")]
		public string COUNTRY
		{
			get
			{
				return this._COUNTRY;
			}
			set
			{
				if ((this._COUNTRY != value))
				{
					this.OnCOUNTRYChanging(value);
					this.SendPropertyChanging();
					this._COUNTRY = value;
					this.SendPropertyChanged("COUNTRY");
					this.OnCOUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMMARY", DbType="NVarChar(1000)")]
		public string SUMMARY
		{
			get
			{
				return this._SUMMARY;
			}
			set
			{
				if ((this._SUMMARY != value))
				{
					this.OnSUMMARYChanging(value);
					this.SendPropertyChanging();
					this._SUMMARY = value;
					this.SendPropertyChanged("SUMMARY");
					this.OnSUMMARYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMG", DbType="Char(100)")]
		public string IMG
		{
			get
			{
				return this._IMG;
			}
			set
			{
				if ((this._IMG != value))
				{
					this.OnIMGChanging(value);
					this.SendPropertyChanging();
					this._IMG = value;
					this.SendPropertyChanged("IMG");
					this.OnIMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(100)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Book")]
	public partial class tbl_Book : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BookID;
		
		private string _BookNAME;
		
		private string _catalo;
		
		private string _AUTHOR;
		
		private System.Nullable<int> _YEAR;
		
		private string _SUMMARY;
		
		private System.Nullable<decimal> _PRICE;
		
		private string _URL;
		
		private string _TRIAL_URL;
		
		private string _IMG;
		
		private string _NOTE;
		
		private System.Nullable<System.DateTime> _DateUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookIDChanging(string value);
    partial void OnBookIDChanged();
    partial void OnBookNAMEChanging(string value);
    partial void OnBookNAMEChanged();
    partial void OncataloChanging(string value);
    partial void OncataloChanged();
    partial void OnAUTHORChanging(string value);
    partial void OnAUTHORChanged();
    partial void OnYEARChanging(System.Nullable<int> value);
    partial void OnYEARChanged();
    partial void OnSUMMARYChanging(string value);
    partial void OnSUMMARYChanged();
    partial void OnPRICEChanging(System.Nullable<decimal> value);
    partial void OnPRICEChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnTRIAL_URLChanging(string value);
    partial void OnTRIAL_URLChanged();
    partial void OnIMGChanging(string value);
    partial void OnIMGChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnDateUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateUpdateChanged();
    #endregion
		
		public tbl_Book()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BookID
		{
			get
			{
				return this._BookID;
			}
			set
			{
				if ((this._BookID != value))
				{
					this.OnBookIDChanging(value);
					this.SendPropertyChanging();
					this._BookID = value;
					this.SendPropertyChanged("BookID");
					this.OnBookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookNAME", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string BookNAME
		{
			get
			{
				return this._BookNAME;
			}
			set
			{
				if ((this._BookNAME != value))
				{
					this.OnBookNAMEChanging(value);
					this.SendPropertyChanging();
					this._BookNAME = value;
					this.SendPropertyChanged("BookNAME");
					this.OnBookNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catalo", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string catalo
		{
			get
			{
				return this._catalo;
			}
			set
			{
				if ((this._catalo != value))
				{
					this.OncataloChanging(value);
					this.SendPropertyChanging();
					this._catalo = value;
					this.SendPropertyChanged("catalo");
					this.OncataloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHOR", DbType="NVarChar(200)")]
		public string AUTHOR
		{
			get
			{
				return this._AUTHOR;
			}
			set
			{
				if ((this._AUTHOR != value))
				{
					this.OnAUTHORChanging(value);
					this.SendPropertyChanging();
					this._AUTHOR = value;
					this.SendPropertyChanged("AUTHOR");
					this.OnAUTHORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Int")]
		public System.Nullable<int> YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMMARY", DbType="NVarChar(2000)")]
		public string SUMMARY
		{
			get
			{
				return this._SUMMARY;
			}
			set
			{
				if ((this._SUMMARY != value))
				{
					this.OnSUMMARYChanging(value);
					this.SendPropertyChanging();
					this._SUMMARY = value;
					this.SendPropertyChanged("SUMMARY");
					this.OnSUMMARYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="Char(1000)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIAL_URL", DbType="Char(1000)")]
		public string TRIAL_URL
		{
			get
			{
				return this._TRIAL_URL;
			}
			set
			{
				if ((this._TRIAL_URL != value))
				{
					this.OnTRIAL_URLChanging(value);
					this.SendPropertyChanging();
					this._TRIAL_URL = value;
					this.SendPropertyChanged("TRIAL_URL");
					this.OnTRIAL_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMG", DbType="Char(100)")]
		public string IMG
		{
			get
			{
				return this._IMG;
			}
			set
			{
				if ((this._IMG != value))
				{
					this.OnIMGChanging(value);
					this.SendPropertyChanging();
					this._IMG = value;
					this.SendPropertyChanged("IMG");
					this.OnIMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(100)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpdate
		{
			get
			{
				return this._DateUpdate;
			}
			set
			{
				if ((this._DateUpdate != value))
				{
					this.OnDateUpdateChanging(value);
					this.SendPropertyChanging();
					this._DateUpdate = value;
					this.SendPropertyChanged("DateUpdate");
					this.OnDateUpdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_BookofUser")]
	public partial class tbl_BookofUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _USERID;
		
		private string _BOOKID;
		
		private System.Nullable<int> _PAGE;
		
		private System.Nullable<System.DateTime> _LastView;
		
		private System.Nullable<char> _Status;
		
		private string _NOTE;
		
		private System.Nullable<System.DateTime> @__Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUSERIDChanging(string value);
    partial void OnUSERIDChanged();
    partial void OnBOOKIDChanging(string value);
    partial void OnBOOKIDChanged();
    partial void OnPAGEChanging(System.Nullable<int> value);
    partial void OnPAGEChanged();
    partial void OnLastViewChanging(System.Nullable<System.DateTime> value);
    partial void OnLastViewChanged();
    partial void OnStatusChanging(System.Nullable<char> value);
    partial void OnStatusChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void On_DateChanging(System.Nullable<System.DateTime> value);
    partial void On_DateChanged();
    #endregion
		
		public tbl_BookofUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="VarChar(15)")]
		public string USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this.OnUSERIDChanging(value);
					this.SendPropertyChanging();
					this._USERID = value;
					this.SendPropertyChanged("USERID");
					this.OnUSERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKID", DbType="NVarChar(10)")]
		public string BOOKID
		{
			get
			{
				return this._BOOKID;
			}
			set
			{
				if ((this._BOOKID != value))
				{
					this.OnBOOKIDChanging(value);
					this.SendPropertyChanging();
					this._BOOKID = value;
					this.SendPropertyChanged("BOOKID");
					this.OnBOOKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAGE", DbType="Int")]
		public System.Nullable<int> PAGE
		{
			get
			{
				return this._PAGE;
			}
			set
			{
				if ((this._PAGE != value))
				{
					this.OnPAGEChanging(value);
					this.SendPropertyChanging();
					this._PAGE = value;
					this.SendPropertyChanged("PAGE");
					this.OnPAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastView", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastView
		{
			get
			{
				return this._LastView;
			}
			set
			{
				if ((this._LastView != value))
				{
					this.OnLastViewChanging(value);
					this.SendPropertyChanging();
					this._LastView = value;
					this.SendPropertyChanged("LastView");
					this.OnLastViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1)")]
		public System.Nullable<char> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="Char(100)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Date]", Storage="__Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> _Date
		{
			get
			{
				return this.@__Date;
			}
			set
			{
				if ((this.@__Date != value))
				{
					this.On_DateChanging(value);
					this.SendPropertyChanging();
					this.@__Date = value;
					this.SendPropertyChanged("_Date");
					this.On_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Catalog")]
	public partial class tbl_Catalog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CatalogID;
		
		private string _CatalogNAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCatalogIDChanging(string value);
    partial void OnCatalogIDChanged();
    partial void OnCatalogNAMEChanging(string value);
    partial void OnCatalogNAMEChanged();
    #endregion
		
		public tbl_Catalog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatalogID", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CatalogID
		{
			get
			{
				return this._CatalogID;
			}
			set
			{
				if ((this._CatalogID != value))
				{
					this.OnCatalogIDChanging(value);
					this.SendPropertyChanging();
					this._CatalogID = value;
					this.SendPropertyChanged("CatalogID");
					this.OnCatalogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatalogNAME", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CatalogNAME
		{
			get
			{
				return this._CatalogNAME;
			}
			set
			{
				if ((this._CatalogNAME != value))
				{
					this.OnCatalogNAMEChanging(value);
					this.SendPropertyChanging();
					this._CatalogNAME = value;
					this.SendPropertyChanged("CatalogNAME");
					this.OnCatalogNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Comment")]
	public partial class tbl_Comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BookID;
		
		private string _AccountID;
		
		private string _Comment;
		
		private int @__Status;
		
		private System.DateTime @__Date;
		
		private string _Note;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookIDChanging(string value);
    partial void OnBookIDChanged();
    partial void OnAccountIDChanging(string value);
    partial void OnAccountIDChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void On_StatusChanging(int value);
    partial void On_StatusChanged();
    partial void On_DateChanging(System.DateTime value);
    partial void On_DateChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    #endregion
		
		public tbl_Comment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BookID
		{
			get
			{
				return this._BookID;
			}
			set
			{
				if ((this._BookID != value))
				{
					this.OnBookIDChanging(value);
					this.SendPropertyChanging();
					this._BookID = value;
					this.SendPropertyChanged("BookID");
					this.OnBookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Status]", Storage="__Status", DbType="Int NOT NULL")]
		public int _Status
		{
			get
			{
				return this.@__Status;
			}
			set
			{
				if ((this.@__Status != value))
				{
					this.On_StatusChanging(value);
					this.SendPropertyChanging();
					this.@__Status = value;
					this.SendPropertyChanged("_Status");
					this.On_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Date]", Storage="__Date", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime _Date
		{
			get
			{
				return this.@__Date;
			}
			set
			{
				if ((this.@__Date != value))
				{
					this.On_DateChanging(value);
					this.SendPropertyChanging();
					this.@__Date = value;
					this.SendPropertyChanged("_Date");
					this.On_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(MAX)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DanhMuc")]
	public partial class tbl_DanhMuc
	{
		
		private string _ID;
		
		private string _Name;
		
		private string _SQL;
		
		private string _Note;
		
		public tbl_DanhMuc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(100)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(300)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQL", DbType="NVarChar(2000)")]
		public string SQL
		{
			get
			{
				return this._SQL;
			}
			set
			{
				if ((this._SQL != value))
				{
					this._SQL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(300)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Follow")]
	public partial class tbl_Follow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AccountID1;
		
		private string _AccountID2;
		
		private int @__Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountID1Changing(string value);
    partial void OnAccountID1Changed();
    partial void OnAccountID2Changing(string value);
    partial void OnAccountID2Changed();
    partial void On_StatusChanging(int value);
    partial void On_StatusChanged();
    #endregion
		
		public tbl_Follow()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID1", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AccountID1
		{
			get
			{
				return this._AccountID1;
			}
			set
			{
				if ((this._AccountID1 != value))
				{
					this.OnAccountID1Changing(value);
					this.SendPropertyChanging();
					this._AccountID1 = value;
					this.SendPropertyChanged("AccountID1");
					this.OnAccountID1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID2", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AccountID2
		{
			get
			{
				return this._AccountID2;
			}
			set
			{
				if ((this._AccountID2 != value))
				{
					this.OnAccountID2Changing(value);
					this.SendPropertyChanging();
					this._AccountID2 = value;
					this.SendPropertyChanged("AccountID2");
					this.OnAccountID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Status]", Storage="__Status", DbType="Int NOT NULL")]
		public int _Status
		{
			get
			{
				return this.@__Status;
			}
			set
			{
				if ((this.@__Status != value))
				{
					this.On_StatusChanging(value);
					this.SendPropertyChanging();
					this.@__Status = value;
					this.SendPropertyChanged("_Status");
					this.On_StatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Package")]
	public partial class tbl_Package
	{
		
		private string _PackageID;
		
		private string _PackageName;
		
		private System.Nullable<decimal> _Amount;
		
		private string _Note;
		
		private string _PackagePrice;
		
		private string _Color;
		
		private System.Nullable<int> _PackageDay;
		
		public tbl_Package()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageID", DbType="Char(10)")]
		public string PackageID
		{
			get
			{
				return this._PackageID;
			}
			set
			{
				if ((this._PackageID != value))
				{
					this._PackageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageName", DbType="NVarChar(200)")]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this._PackageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(200)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackagePrice", DbType="NVarChar(50)")]
		public string PackagePrice
		{
			get
			{
				return this._PackagePrice;
			}
			set
			{
				if ((this._PackagePrice != value))
				{
					this._PackagePrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="Char(20)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageDay", DbType="Int")]
		public System.Nullable<int> PackageDay
		{
			get
			{
				return this._PackageDay;
			}
			set
			{
				if ((this._PackageDay != value))
				{
					this._PackageDay = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Rating")]
	public partial class tbl_Rating : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AccountID;
		
		private string _BookID;
		
		private int _Rating;
		
		private System.Nullable<System.DateTime> @__Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIDChanging(string value);
    partial void OnAccountIDChanged();
    partial void OnBookIDChanging(string value);
    partial void OnBookIDChanged();
    partial void OnRatingChanging(int value);
    partial void OnRatingChanged();
    partial void On_DateChanging(System.Nullable<System.DateTime> value);
    partial void On_DateChanged();
    #endregion
		
		public tbl_Rating()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BookID
		{
			get
			{
				return this._BookID;
			}
			set
			{
				if ((this._BookID != value))
				{
					this.OnBookIDChanging(value);
					this.SendPropertyChanging();
					this._BookID = value;
					this.SendPropertyChanged("BookID");
					this.OnBookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int NOT NULL")]
		public int Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Date]", Storage="__Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> _Date
		{
			get
			{
				return this.@__Date;
			}
			set
			{
				if ((this.@__Date != value))
				{
					this.On_DateChanging(value);
					this.SendPropertyChanging();
					this.@__Date = value;
					this.SendPropertyChanged("_Date");
					this.On_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TransactionHistory")]
	public partial class tbl_TransactionHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TransactionID;
		
		private string _TransactionName;
		
		private string _AccountID;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<System.DateTime> _TransactionDate;
		
		private string _Note;
		
		private System.Nullable<decimal> _Discount;
		
		private string _DiscountName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    partial void OnTransactionNameChanging(string value);
    partial void OnTransactionNameChanged();
    partial void OnAccountIDChanging(string value);
    partial void OnAccountIDChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnTransactionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTransactionDateChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnDiscountChanging(System.Nullable<decimal> value);
    partial void OnDiscountChanged();
    partial void OnDiscountNameChanging(string value);
    partial void OnDiscountNameChanged();
    #endregion
		
		public tbl_TransactionHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this.OnTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._TransactionID = value;
					this.SendPropertyChanged("TransactionID");
					this.OnTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionName", DbType="NVarChar(250)")]
		public string TransactionName
		{
			get
			{
				return this._TransactionName;
			}
			set
			{
				if ((this._TransactionName != value))
				{
					this.OnTransactionNameChanging(value);
					this.SendPropertyChanging();
					this._TransactionName = value;
					this.SendPropertyChanged("TransactionName");
					this.OnTransactionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="VarChar(15)")]
		public string AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TransactionDate
		{
			get
			{
				return this._TransactionDate;
			}
			set
			{
				if ((this._TransactionDate != value))
				{
					this.OnTransactionDateChanging(value);
					this.SendPropertyChanging();
					this._TransactionDate = value;
					this.SendPropertyChanged("TransactionDate");
					this.OnTransactionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(200)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this.OnDiscountChanging(value);
					this.SendPropertyChanging();
					this._Discount = value;
					this.SendPropertyChanged("Discount");
					this.OnDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string DiscountName
		{
			get
			{
				return this._DiscountName;
			}
			set
			{
				if ((this._DiscountName != value))
				{
					this.OnDiscountNameChanging(value);
					this.SendPropertyChanging();
					this._DiscountName = value;
					this.SendPropertyChanged("DiscountName");
					this.OnDiscountNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
