<?xml version="1.0" encoding="utf-8"?><Database Name="BookOnline" Class="DataClassesBookOnlineDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-R673IG9\SQLEXPRESS;Initial Catalog=BookOnline;Integrated Security=True" SettingsObjectName="DAL_BookOnline.Properties.Settings" SettingsPropertyName="BookOnlineConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Account" Member="tbl_Accounts">
    <Type Name="tbl_Account">
      <Column Name="AccountID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PWD" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="GEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Wallet" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="IMG" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NOTE" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="RemainingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SignupDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TransactionInfo" Member="tbl_TransactionInfos">
    <Type Name="tbl_TransactionInfo">
      <Column Name="TransactionID" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Annotation" Member="tbl_Annotations">
    <Type Name="tbl_Annotation">
      <Column Name="Annotation_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="book_id" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="book_name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="user_id" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Annotation_text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="page_number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Annotation_type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Annotation_color" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="creationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modificationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="QX1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="qy1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="qx2" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="qy2" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="qx3" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="qy3" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="qx4" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="qy4" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Annotation_Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Author" Member="tbl_Authors">
    <Type Name="tbl_Author">
      <Column Name="AuthorID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AuthorNAME" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="GEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BIRTHDAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="COUNTRY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SUMMARY" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IMG" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Book" Member="tbl_Books">
    <Type Name="tbl_Book">
      <Column Name="BookID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookNAME" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="catalo" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LangID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="AUTHOR" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="YEAR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUMMARY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="Char(1000)" CanBeNull="true" />
      <Column Name="TRIAL_URL" Type="System.String" DbType="Char(1000)" CanBeNull="true" />
      <Column Name="IMG" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BookofUser" Member="tbl_BookofUsers">
    <Type Name="tbl_BookofUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BOOKID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PAGE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastView" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="[_Date]" Member="_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BookPublisher" Member="tbl_BookPublishers">
    <Type Name="tbl_BookPublisher">
      <Column Name="BookID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PublisherID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BranchPayment" Member="tbl_BranchPayments">
    <Type Name="tbl_BranchPayment">
      <Column Name="BranchCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Catalog" Member="tbl_Catalogs">
    <Type Name="tbl_Catalog">
      <Column Name="CatalogID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CatalogNAME" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Comment" Member="tbl_Comments">
    <Type Name="tbl_Comment">
      <Column Name="BookID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="[_Status]" Member="_Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_Date]" Member="_Date" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DanhMuc" Member="tbl_DanhMucs">
    <Type Name="tbl_DanhMuc">
      <Column Name="ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="SQL" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Follow" Member="tbl_Follows">
    <Type Name="tbl_Follow">
      <Column Name="AccountID1" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountID2" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[_Status]" Member="_Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Language" Member="tbl_Languages">
    <Type Name="tbl_Language">
      <Column Name="LangID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LangName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Mapping" Member="tbl_Mappings">
    <Type Name="tbl_Mapping">
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Version" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Package" Member="tbl_Packages">
    <Type Name="tbl_Package">
      <Column Name="PackageID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="PackageName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PackagePrice" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="PackageDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Publisher" Member="tbl_Publishers">
    <Type Name="tbl_Publisher">
      <Column Name="PublisherID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PublisherName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="[E-mail]" Member="E_mail" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="Char(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Rating" Member="tbl_Ratings">
    <Type Name="tbl_Rating">
      <Column Name="AccountID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_Date]" Member="_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TransactionHistory" Member="tbl_TransactionHistories">
    <Type Name="tbl_TransactionHistory">
      <Column Name="TransactionID" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AccountID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DiscountName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>