//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUBookOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookOnlineEntities : DbContext
    {
        public BookOnlineEntities()
            : base("name=BookOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Account> tbl_Account { get; set; }
        public virtual DbSet<tbl_Annotation> tbl_Annotation { get; set; }
        public virtual DbSet<tbl_Author> tbl_Author { get; set; }
        public virtual DbSet<tbl_Book> tbl_Book { get; set; }
        public virtual DbSet<tbl_BookPublisher> tbl_BookPublisher { get; set; }
        public virtual DbSet<tbl_Catalog> tbl_Catalog { get; set; }
        public virtual DbSet<tbl_Comment> tbl_Comment { get; set; }
        public virtual DbSet<tbl_Follow> tbl_Follow { get; set; }
        public virtual DbSet<tbl_Language> tbl_Language { get; set; }
        public virtual DbSet<tbl_Publisher> tbl_Publisher { get; set; }
        public virtual DbSet<tbl_Rating> tbl_Rating { get; set; }
        public virtual DbSet<tbl_TransactionHistory> tbl_TransactionHistory { get; set; }
        public virtual DbSet<tbl_TransactionInfo> tbl_TransactionInfo { get; set; }
        public virtual DbSet<tbl_Mapping> tbl_Mapping { get; set; }
        public virtual DbSet<tbl_BookofUser> tbl_BookofUser { get; set; }
    }
}
