//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUBookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransactionHistory
    {
        public string TransactionID { get; set; }
        public string TransactionName { get; set; }
        public string AccountID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string DiscountName { get; set; }
    }
}
