//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUBookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransactionInfo
    {
        public string TransactionID { get; set; }
        public string ProductID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
