//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUBookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BookofUser
    {
        public int ID { get; set; }
        public string USERID { get; set; }
        public string BOOKID { get; set; }
        public Nullable<int> PAGE { get; set; }
        public Nullable<System.DateTime> LastView { get; set; }
        public string Status { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
    }
}
