//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUBookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Annotation
    {
        public int Annotation_id { get; set; }
        public string book_id { get; set; }
        public string book_name { get; set; }
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string Annotation_text { get; set; }
        public Nullable<int> page_number { get; set; }
        public string Annotation_type { get; set; }
        public string Annotation_color { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> QX1 { get; set; }
        public Nullable<decimal> qy1 { get; set; }
        public Nullable<decimal> qx2 { get; set; }
        public Nullable<decimal> qy2 { get; set; }
        public Nullable<decimal> qx3 { get; set; }
        public Nullable<decimal> qy3 { get; set; }
        public Nullable<decimal> qx4 { get; set; }
        public Nullable<decimal> qy4 { get; set; }
        public string Annotation_Comment { get; set; }
    }
}
