//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUBookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Book
    {
        public string BookID { get; set; }
        public string BookNAME { get; set; }
        public string catalo { get; set; }
        public string LangID { get; set; }
        public string AUTHOR { get; set; }
        public Nullable<int> YEAR { get; set; }
        public string SUMMARY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string URL { get; set; }
        public string TRIAL_URL { get; set; }
        public string IMG { get; set; }
        public string NOTE { get; set; }
        public System.DateTime DateUpdate { get; set; }
    }
}
