//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUBookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Author
    {
        public string AuthorID { get; set; }
        public string AuthorNAME { get; set; }
        public Nullable<bool> GEN { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string COUNTRY { get; set; }
        public string SUMMARY { get; set; }
        public string IMG { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
