//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUBookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account
    {
        public string AccountID { get; set; }
        public string NAME { get; set; }
        public string PWD { get; set; }
        public bool GEN { get; set; }
        public Nullable<decimal> Wallet { get; set; }
        public byte[] IMG { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> RemainingTime { get; set; }
        public int Status { get; set; }
        public System.DateTime SignupDate { get; set; }
    }
}
